/*
 * This file is part of WebCL – Web Computing Language.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL
 * was not distributed with this file, You can obtain
 * one at http://mozilla.org/MPL/2.0/.
 *
 * The Original Contributor of this Source Code Form is
 * Nokia Research Center Tampere (http://webcl.nokiaresearch.com).
 *
 */

#include "nsISupports.idl"
#include "nsIVariant.idl"
#include "interfaces/webcl_types.idl"

#include "interfaces/IWebCLDevice.idl"
#include "interfaces/IWebCLKernel.idl"

typedef nsIVariant IWebCLDevice_List;
typedef nsIVariant WebCLCallback;
typedef nsIVariant IWebCLKernel_List;

[scriptable, uuid(74d49a1e-31e0-41d5-8e98-8980a077fcb2)]
interface IWebCLProgram : nsISupports
{
  string getExternalIdentity ();
  nsIVariant getInfo (in CLenum name);

  nsIVariant getBuildInfo (in IWebCLDevice device, in CLenum name);

  void build ([optional] in IWebCLDevice_List devices,
              [optional] in string options,
              [optional] in WebCLCallback whenFinished);

  IWebCLKernel createKernel (in string kernelName);

  IWebCLKernel_List createKernelsInProgram ();

  void release ();
};
