/*
 * This file is part of WebCL – Web Computing Language.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL
 * was not distributed with this file, You can obtain
 * one at http://mozilla.org/MPL/2.0/.
 *
 * The Original Contributor of this Source Code Form is
 * Nokia Research Center Tampere (http://webcl.nokiaresearch.com).
 *
 */

#include "nsISupports.idl"
#include "interfaces/webcl_types.idl"

[scriptable, uuid(8f865901-2efb-422e-bb15-26e0beb0c845)]
interface IWebCLImageDescriptor : nsISupports
{
  string getExternalIdentity ();

  attribute CLenum channelOrder;
  attribute CLenum channelType;
  attribute CLuint width;
  attribute CLuint height;
  attribute CLuint rowPitch;
};
