/*
 * This file is part of WebCL – Web Computing Language.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL
 * was not distributed with this file, You can obtain
 * one at http://mozilla.org/MPL/2.0/.
 *
 * The Original Contributor of this Source Code Form is
 * Nokia Research Center Tampere (http://webcl.nokiaresearch.com).
 *
 */

#include "nsISupports.idl"
#include "nsIVariant.idl"
#include "interfaces/webcl_types.idl"

[scriptable, uuid(6ab8b8cf-4d87-40a0-af8a-cc0bf5251fa3)]
interface IWebCLPlatform : nsISupports
{
  string getExternalIdentity ();
  nsIVariant getInfo (in CLenum name);
  nsIVariant getDevices ([optional] in CLenum deviceType);
  nsIVariant getSupportedExtensions ();
  CLboolean enableExtension (in string extensionName);
};
