/*
 * This file is part of WebCL – Web Computing Language.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL
 * was not distributed with this file, You can obtain
 * one at http://mozilla.org/MPL/2.0/.
 *
 * The Original Contributor of this Source Code Form is
 * Nokia Research Center Tampere (http://webcl.nokiaresearch.com).
 *
 */

#include "nsISupports.idl"
#include "nsIException.idl"

[scriptable, uuid(68247317-c897-4ab1-bace-44126583ba42)]
interface IWebCLException : nsIException
{
  //readonly attribute string name;
  //readonly attribute string message;
};


[scriptable, uuid(2e5d5f94-6f88-4ced-9dcf-52005d85c289)]
interface IWebCLNotImplementedException : IWebCLException
{
};


[scriptable, uuid(e30380ae-8b70-4d25-ac26-5288c0131bd4)]
interface IWebCLInvalidArgumentException : IWebCLException
{
};


[scriptable, uuid(b683a418-4760-4c61-8358-8a6d28846516)]
interface IWebCLInternalErrorException : IWebCLException
{
};

