/*
 * This file is part of WebCL – Web Computing Language.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL
 * was not distributed with this file, You can obtain
 * one at http://mozilla.org/MPL/2.0/.
 *
 * The Original Contributor of this Source Code Form is
 * Nokia Research Center Tampere (http://webcl.nokiaresearch.com).
 *
 */

#include "nsISupports.idl"
#include "nsIVariant.idl"
#include "interfaces/webcl_types.idl"
//#include "interfaces/IWebCLMemoryObject.idl"

#include "interfaces/IWebCLImageDescriptor.idl"

// NOTE: Can't inherit from IWebCLMemoryObject since getInfo is incompatible
//       and would not be overridden.
[scriptable, uuid(af42d437-b62c-43de-985c-c65e28a82ead)]
interface IWebCLImage : nsISupports
{
  string getExternalIdentity ();
  nsIVariant getInfo([optional] in CLenum name);
  void release ();
};
