/*
 * This file is part of WebCL – Web Computing Language.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL
 * was not distributed with this file, You can obtain
 * one at http://mozilla.org/MPL/2.0/.
 *
 * The Original Contributor of this Source Code Form is
 * Nokia Research Center Tampere (http://webcl.nokiaresearch.com).
 *
 */

#include "nsISupports.idl"
#include "nsIVariant.idl"
#include "interfaces/webcl_types.idl"

typedef nsIVariant WebCLCallback;

[scriptable, uuid(cf7372e6-f2ec-467d-99dc-9eeb756bc3e3)]
interface IWebCLEvent : nsISupports
{
  nsIVariant getInfo (in CLenum name);
  nsIVariant getProfilingInfo (in CLenum name);
  void setCallback (in CLenum commandExecCallbackType, in WebCLCallback notify);
  void release ();
};


[scriptable, uuid(f353b7e7-03af-41f2-a260-5cbcdaec8ae9)]
interface IWebCLUserEvent : IWebCLEvent
{
  void setUserEventStatus (in CLenum executionStatus);
};
