/*
 * This file is part of WebCL – Web Computing Language.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL
 * was not distributed with this file, You can obtain
 * one at http://mozilla.org/MPL/2.0/.
 *
 * The Original Contributor of this Source Code Form is
 * Nokia Research Center Tampere (http://webcl.nokiaresearch.com).
 *
 */

// See WebCL Working Draft:
// https://cvs.khronos.org/svn/repos/registry/trunk/public/webcl/spec/latest/index.html

typedef boolean       CLboolean;
typedef long          CLint;
typedef unsigned long CLuint;
typedef unsigned long CLenum;
