/*
 * This file is part of WebCL – Web Computing Language.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL
 * was not distributed with this file, You can obtain
 * one at http://mozilla.org/MPL/2.0/.
 *
 * The Original Contributor of this Source Code Form is
 * Nokia Research Center Tampere (http://webcl.nokiaresearch.com).
 *
 */

/** \interface IWebCLDevice
 * IWebCLDevice interface abstracts a WebCL device.
 * \see cl_device_id
 */

#include "nsISupports.idl"
#include "nsISecurityCheckedComponent.idl"
#include "nsIVariant.idl"

#include "WebCL_types.idl"

[scriptable, uuid(f5352722-9a35-405b-95ae-54d5b4995576)]
interface IWebCLDevice : nsISecurityCheckedComponent
{
  /** Get device info.
   * \param aName Name of the info parameter.
   * \return The resulting value.
   * \see clGetDeviceInfo
   * \see WebCL_types
   */
  [implicit_jscontext]
  nsIVariant getDeviceInfo (in long aName);

  [implicit_jscontext] void setAttachment (in nsIVariant aValue);
  [implicit_jscontext] nsIVariant getAttachment ();
};
