/*
 * This file is part of WebCL – Web Computing Language.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL 
 * was not distributed with this file, You can obtain 
 * one at http://mozilla.org/MPL/2.0/.
 *
 * The Original Contributor of this Source Code Form is
 * Nokia Research Center Tampere (http://webcl.nokiaresearch.com).
 *
 */

/** \interface IWebCLPlatform
 * IWebCLPlatform interface abstracts a WebCL platform.
 * \see cl_platform_id
 */

#include "nsISupports.idl"
#include "nsISecurityCheckedComponent.idl"
#include "nsIVariant.idl"

#include "WebCL_types.idl"

[scriptable, uuid(6ab8b8cf-4d87-40a0-af8a-cc0bf5251fa3)]
interface IWebCLPlatform : nsISecurityCheckedComponent
{
  /** Get platform info.
   * \param aName Name of the info parameter.
   * \return The resulting value.
   * \see clGetPlatformInfo
   * \see WebCL_types
   */
  [implicit_jscontext]
  nsIVariant getPlatformInfo (in long aName);

  /** Obtain the list of devices available on a platform.
   * \param aType A bitfield that identifies the type of OpenCL device.
   * \return Array of IWebCLDevice instances.
   * \see clGetDeviceIDs
   */
  [implicit_jscontext]
  nsIVariant getDeviceIDs (in T_WebCLDeviceType aType);

  [implicit_jscontext]
  nsIVariant getDevices (in T_WebCLDeviceType aType);
};
