/*
 * This file is part of WebCL – Web Computing Language.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL
 * was not distributed with this file, You can obtain
 * one at http://mozilla.org/MPL/2.0/.
 *
 * The Original Contributor of this Source Code Form is
 * Nokia Research Center Tampere (http://webcl.nokiaresearch.com).
 *
 */

/** \interface IWebCLMemoryObject
 * IWebCLMemoryObject interface abstracts a WebCL memory object such as
 * a buffer or an image.
 * \see cl_mem
 */

#include "nsISupports.idl"
#include "nsISecurityCheckedComponent.idl"
#include "nsIVariant.idl"

#include "WebCL_types.idl"

[scriptable, uuid(e677e482-49e5-40de-ba4f-0e71f301286b)]
interface IWebCLMemoryObject : nsISecurityCheckedComponent
{
  /** Get memory object info.
   * \param aName Name of the info parameter.
   * \return The resulting value.
   * \see clGetMemObjectInfo
   * \see WebCL_types
   */
  [implicit_jscontext]
  nsIVariant getMemObjectInfo (in long aName);

  /** Get image info.
   * \param aName Name of the info parameter.
   * \return The resulting value.
   * \see clGetImageInfo
   * \see WebCL_types
   */
  [implicit_jscontext]
  nsIVariant getImageInfo (in long aName);

  /** Creates a buffer object (referred to as a sub-buffer object) from
   * an existing buffer object.
   * \param aFlags A bit-field that is used to specify allocation and
   *  usage information about the image memory object being created.
   * \param aBufferRegion An object with "size" and "origin" properties of integer type.
   * \see clCreateSubBuffer
   */
  [implicit_jscontext]
  IWebCLMemoryObject createSubBuffer (in T_WebCLMemFlags aFlags,
                                      in nsIVariant aBufferRegion);

  /** Immediately releases all OpenCL-related resources if any are allocated
   * for this object. The object should not be used anymore after calling
   * this function.
   */
  void releaseCLResources ();

  [implicit_jscontext] void setAttachment (in nsIVariant aValue);
  [implicit_jscontext] nsIVariant getAttachment ();
};
