/*
 * This file is part of WebCL – Web Computing Language.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL 
 * was not distributed with this file, You can obtain 
 * one at http://mozilla.org/MPL/2.0/.
 *
 * The Original Contributor of this Source Code Form is
 * Nokia Research Center Tampere (http://webcl.nokiaresearch.com).
 *
 */

/** \interface IWebCLSampler
 * IWebCLSampler interface abstracts a WebCL sampler.
 * \see cl_sampler
 */

#include "nsISupports.idl"
#include "nsISecurityCheckedComponent.idl"
#include "nsIVariant.idl"

#include "WebCL_types.idl"

[scriptable, uuid(dc9b25aa-2bdc-4efd-b295-b450c75d252c)]
interface IWebCLSampler : nsISecurityCheckedComponent
{
  /** Get sampler info.
   * \param aName Name of the info parameter.
   * \return The resulting value.
   * \see clGetSamplerInfo
   * \see WebCL_types
   */
  [implicit_jscontext]
  nsIVariant getSamplerInfo (in long aName);

  /** Immediately releases all OpenCL-related resources if any are allocated
   * for this object. The object should not be used anymore after calling
   * this function.
   */
  void releaseCLResources ();
};
