/*
 * This file is part of WebCL – Web Computing Language.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL 
 * was not distributed with this file, You can obtain 
 * one at http://mozilla.org/MPL/2.0/.
 *
 * The Original Contributor of this Source Code Form is
 * Nokia Research Center Tampere (http://webcl.nokiaresearch.com).
 *
 */

/**
 * WebCL types.
 * The types listed in this file are used on WebCL interface definitions.
 */

//typedef unsigned long           T_WebCLBitField;
typedef unsigned long           T_WebCLSize;

// Enumerated types
typedef long                    T_WebCLEnum;
typedef T_WebCLEnum             T_WebCLAddressingMode;
typedef T_WebCLEnum             T_WebCLBufferCreateType;
typedef T_WebCLEnum             T_WebCLBuildStatus;
typedef T_WebCLEnum             T_WebCLChannelOrder;
typedef T_WebCLEnum             T_WebCLChannelType;
typedef T_WebCLEnum             T_WebCLCommandQueueInfo;
typedef T_WebCLEnum             T_WebCLCommandQueueProperties;
typedef T_WebCLEnum             T_WebCLCommandType;
typedef T_WebCLEnum             T_WebCLContextInfo;
typedef T_WebCLEnum             T_WebCLContextProperties;
typedef T_WebCLEnum             T_WebCLDeviceExecCapabilities;
typedef T_WebCLEnum             T_WebCLDeviceFPConfig;
typedef T_WebCLEnum             T_WebCLDeviceInfo;
typedef T_WebCLEnum             T_WebCLDeviceLocalMemType;
typedef T_WebCLEnum             T_WebCLDeviceMemCacheType;
typedef T_WebCLEnum             T_WebCLDeviceType;
typedef T_WebCLEnum             T_WebCLEventInfo;
typedef T_WebCLEnum             T_WebCLFilterMode;
typedef T_WebCLEnum             T_WebCLGLObjectType;
typedef T_WebCLEnum             T_WebCLGLTextureInfo;
typedef T_WebCLEnum             T_WebCLImageInfo;
typedef T_WebCLEnum             T_WebCLKernelInfo;
typedef T_WebCLEnum             T_WebCLKernelWorkGroupInfo;
typedef T_WebCLEnum             T_WebCLMapFlags;
typedef T_WebCLEnum             T_WebCLFenceFlags;
typedef T_WebCLEnum             T_WebCLMemFlags;
typedef T_WebCLEnum             T_WebCLMemInfo;
typedef T_WebCLEnum             T_WebCLMemObjectType;
typedef T_WebCLEnum             T_WebCLPlatformInfo;
typedef T_WebCLEnum             T_WebCLProfilingInfo;
typedef T_WebCLEnum             T_WebCLProgramBuildInfo;
typedef T_WebCLEnum             T_WebCLSamplerInfo;
