/*
 * This file is part of WebCL – Web Computing Language.
 *
 * This Source Code Form is subject to the terms of the
 * Mozilla Public License, v. 2.0. If a copy of the MPL 
 * was not distributed with this file, You can obtain 
 * one at http://mozilla.org/MPL/2.0/.
 *
 * The Original Contributor of this Source Code Form is
 * Nokia Research Center Tampere (http://webcl.nokiaresearch.com).
 *
 */

/**
 * WebCL IDLs.
 * Other XPCOM components can use this file can be used for including all
 * WebCL IDL files and their dependencies at the same time.
 */

#include "nsISupports.idl"
#include "nsISecurityCheckedComponent.idl"
#include "nsIVariant.idl"

#include "WebCL_types.idl"

#include "IWebCL.idl"
#include "IWebCLPlatform.idl"
#include "IWebCLContext.idl"
#include "IWebCLDevice.idl"
#include "IWebCLMemoryObject.idl"
#include "IWebCLCommandQueue.idl"
#include "IWebCLEvent.idl"
#include "IWebCLProgram.idl"
#include "IWebCLKernel.idl"
#include "IWebCLSampler.idl"
